import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar, Navbar, Footer } from "@/app/components/generales";



const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Puedes agregar más pesos si los necesitas
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"], // Agrega más pesos si los necesitas
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
      <Navbar></Navbar>
      <div className="flex flex-row">
      <Sidebar></Sidebar>
      <main className="flex-1 p-6">{children}</main> {/* Rutas aquí */}
      </div>
      <Footer></Footer>
      </body>
    </html>
  );
}
